### ISSUE TITLE
Error on QA service interface

### ISSUE THREAD

**Issue by cbadenes** [drugs4covid/web#45]
vue.runtime.esm.js:3019 TypeError: Cannot read properties of undefined (reading 'api')
    at Object.F [as qaAnswers] (axiosService.js:37:32)
    at o.askQuestion (QAView.vue:107:1)
    at click (QAView.vue:1:926)
    at qt (vue.runtime.esm.js:2987:30)
    at o.n (vue.runtime.esm.js:1785:20)
    at qt (vue.runtime.esm.js:2987:30)
    at e.$emit (vue.runtime.esm.js:3685:17)
    at o.click (VBtn.ts:163:12)
    at qt (vue.runtime.esm.js:2987:30)
    at HTMLButtonElement.n (vue.runtime.esm.js:1785:20)

**Comment by Vitoriox** [comment]
This issue was already solved when working on #43. 
It will be working properly in the next production build
